version: "3.8"
services:
  jenkins:
    build: jenkins
    env_file: jenkins.env
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    networks:
      - jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jenkins/casc.yaml:/var/jenkins_home/casc.yaml
      - docker:/var/run/
    depends_on:
      - dind

  dind:
    image: docker:20.10-dind
    container_name: dind
    privileged: true
    volumes:
      - docker:/var/run/
    networks:
      - jenkins

networks:
  jenkins:
    name: jenkins
    driver: bridge
volumes:
  jenkins_home:
    name: jenkins_home
    driver: local
  docker:
    name: docker
    driver: local
