version: "3.8"
services:
  jenkins:
    build: jenkins
    env_file: jenkins.env
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    networks:
      - jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jenkins/casc.yaml:/var/jenkins_home/casc.yaml
      - docker:/var/run/
    depends_on:
      - dind

  dind:
    image: docker:20.10-dind
    container_name: dind
    privileged: true
    volumes:
      - docker:/var/run/
    networks:
      - jenkins

  db:
    image: postgres:16
    container_name: db
    restart: always
    networks:
      - jenkins
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - postgresql:/var/lib/postgresql

  sonarqube:
    image: sonarqube:9.9.5-community
    container_name: sonarqube
    ports:
      - 9000:9000
    networks:
      - jenkins
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    depends_on:
      - db
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

networks:
  jenkins:
    name: jenkins
    driver: bridge

volumes:
  jenkins_home:
    name: jenkins_home
    driver: local
  docker:
    name: docker
    driver: local
  postgresql:
    name: postgresql
    driver: local
  sonarqube_conf:
    name: sonarqube_conf
    driver: local
  sonarqube_data:
    name: sonarqube_data
    driver: local
  sonarqube_extensions:
    name: sonarqube_extensions
    driver: local
  sonarqube_bundled-plugins:
    name: sonarqube_bundled-plugins
    driver: local
